baseurl      = "https://cv.erikartaz.work/"
title        = "Erik Artaz"
languageCode = "it-IT"
theme        = "hello-friend-ng"
pagination.pagerSize = 10

[module]
  [[module.mounts]]
    disableWatch = false
    lang = ''
    source = 'assets'
    target = 'assets'

[params.portrait]
  path     = "/assets/images/portrait.jpg"
  alt      = "Portrait"
  maxWidth = "250px"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "I'm a cloud FinOps guy!"

  logoText = "hello friend ng"
  logoHomeLink = "/"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  backgroundImage = "assets/images/background.jpg"
  enableThemeToggle = false


[markup.goldmark.renderer]
  hardWraps = false
  unsafe = true
  xhtml = false  


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


[[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/posts"

[[menu.main]]
  identifier = "cvit"
  name       = "CV it"
  url        = "/pages/cv"

[[menu.main]]
identifier = "cven"
name       = "CV en"
url        = "/pages/cven"
