baseurl      = "https://cv.erikartaz.work/"
title        = "Erik Artaz"
languageCode = "it-it"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10



backgroundImage = "assets/images/background.jpg"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "La tana del bianconiglio"

  logoText = "hello friend ng"
  logoHomeLink = "/"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]
  

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"




  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

    # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/pages/cv"
